apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: beautysalon-employees-api
  namespace: flux-system
spec:
  interval: 1m0s
  image: woogie42/beautysalon.employees.api