redis:
  enabled: true
  password: guest
persistence:
  enabled: true
  size: 5Gi
  storageClass: hostpath
postgres:
  user: postgres
  password: 1234
  database: BeautySalonEmployeesDb
image:
  repository: woogie42/beautysalon.employees.api
  tag: ab0b25f7725dce10243a62aa04ea7f9a1e8ca1ee-134
