apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/image-tag: "{{ .Values.image.tag }}"
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: Redis__ConnectionString
              value: "{{ .Release.Name }}-redis:{{ .Values.redis.port }},abortConnect=false" 
            - name: Redis__Password
              value: "{{ .Values.redis.password }}"
            
            - name: POSTGRES_HOST
              value: "{{ .Release.Name }}-postgres"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
            
          ports:
            - containerPort: 8080
          