apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: booking-service
  namespace: default
spec:
  chart:
    spec:
      chart: ./k8s/bookingHelm
      sourceRef:
        kind: GitRepository
        name: beauty-salon-repo
        namespace: flux-system
      valuesFiles:
        - values.yaml
      reconcileStrategy: Revision  
  interval: 5m

