apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: employees-service
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./k8s/employeesHelm
      sourceRef:
        kind: GitRepository
        name: beauty-salon-repo
        namespace: flux-system
      valuesFiles:
        - values.yaml

