apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
    - name: management
      port: {{ .Values.service.managementPort }}
  type: {{ .Values.service.type }}

