apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: beauty-salon-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: git@github.com:Woogie7/BeautySalon.Deployments.git
  ref:
    branch: main
  secretRef:
    name: flux-git-deploy