apiVersion: source.toolkit.fluxcd.io/v2
kind: GitRepository
metadata:
  name: beauty-salon-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/Woogie7/BeautySalon.Deployments.git
  secretRef:
    name: flux-git-deploy
  ref:
    branch: main
