apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: beautysalon-booking-api-policy
  namespace: default
spec:
  imageRepositoryRef:
    name: beautysalon-booking-api
  policy:
    tag:
      kind: semver # Или 'regex' для регулярных выражений
      pattern: '^[0-9a-f]{40}$' # Регулярное выражение для SHA-хэшей