apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: beautysalon-booking-api-update
  namespace: default
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: beauty-salon-repo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main 
  update:
    path: bookingHelm/values.yaml
    strategy: Setters