apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: beautysalon-booking-api
  namespace: default
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: beauty-salon-repo
    namespace: flux-system
  image: woogie42/beautysalon.booking.api
  