apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: beautysalon-booking-api-update
  namespace: default
spec:
  sourceRef:
    kind: GitRepository
    name: beauty-salon-repo
  git:
    ref:
      branch: main
  interval: 1m0s # Интервал проверки
  update:
    strategy: Setters
    setters:
      - name: IMAGE_TAG
        valueFrom:
          imageMetadata:
            name: woogie42/beautysalon.booking.api
            tag: latest