apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: beautysalon-authandclient-api-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: beautysalon-authandclient-api
  filterTags:
    pattern: '^[a-f0-9]+-(?P<ts>[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc