apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : employee-service-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: default
  source:
    path   : "k8s"
    repoURL: "git@github.com:Woogie7/BeautySalon.Deployments.gitt"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true