apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : employee-service-api
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app1
  source:
    path   : "k8s"
    repoURL: "git@github.com:Woogie7/BeautySalon.Deployments.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml
      parameters:
      - name: "container.image"
        value: adv4000/app1:v3

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 