apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: rabbitmq
    targetRevision: 16.0.1
    helm:
      valueFiles:
        - ../../k8s/rabbitmq/values.yaml 
      parameters:
        - name: fullnameOverride
          value: rabbitmq
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
