apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/bitnami/charts.git
    path: bitnami/rabbitmq
    targetRevision: main # или конкретный тег/commit
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
