apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: "beauty-salon-booking"
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
          - name: postgres
            image: postgres:15
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_USER
                value: "{{ .Values.postgres.user }}"
              - name: POSTGRES_PASSWORD
                value: "{{ .Values.postgres.password }}"
              - name: POSTGRES_DB
                value: "{{ .Values.postgres.database }}"
            volumeMounts:
              - name: postgres-employees-pvc
                mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-employees-pvc
          persistentVolumeClaim:
            claimName: postgres-employees-pvc
          
          
