redis:
  enabled: true
  password: guest
  port: 6377
persistence:
  enabled: true
  size: 5Gi
  storageClass: hostpath
postgres:
  user: postgres
  password: 1234
  database: BeautySalonBookingDb
image:
  repository: woogie42/beautysalon.booking.api
  tag: c53285b35469853063474af1782d576ecc783771
