redis:
  enabled: true
  password: guest
postgres:
  user: postgres
  password: 1234
  database: BeautySalonBookingDb
image:
  repository: woogie42/beautysalon.booking.api
  tag: beafb41d1f35926e6b37d80c08d4e7091fdfa98c
